version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 54321:54321
    volumes:
      - ./prisma/seeds:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: -p 54321
